version: '3'
services:
  nginx:
    image: nginx:alpine
  port:
    - "80:80"
    - "443:443"
  volumes: 
    - ./html:/usr/share/nginx/html:rw
    - ./conf.d:/etc/nginx/conf.d:rw
    
  cerbot:
    image: certbot/certbot
    volumes: 
      - ./letsencrypt/etc:/etc/letsencrypt
      - ./letsencrypt/var/lib/:/var/lib/letsencrypt
      - ./html:/data/letsencrypt:rw
